baseURL = "https://www.theitxp.com"
languageCode = "en-us"
title = "The IT XP"
theme = "castanet"
googleAnalytics = ""
disqusShortname = ""

[params]
site_theme = "blue"
site_layout = "grid"
enable_jumbo = "true"
favicon = "favicon.ico"
description = "This is the home of the The IT XP, a show dedicated to the world of Information Technology and the professionals working to drive business initiatives using their technology skills."
copyright_notice = "Copyright 2015 COTIB LLC"

[params.social]
twitter = "@theitxp"
youtube = "@theitxp"

[params.authors]
[params.authors.YourName]
name = "Chuck"
thumbnail = "img/host/your-image.jpg"
bio = "Pulling back the curtains and exposing some of the inner workings of what it’s like to work in Tech."

[params.links]
[params.links.youtube]
name = "YouTube"
url = "https://www.youtube.com/@theitxp"